### ISSUE TITLE
Check for null values in TaskName

### ISSUE THREAD

**Issue by Shubhi-Paul** [ACM-VIT/10-000-Hours#15]
Bug :  task getting added to taskList even if there is no name

> In lib>providers>task_list_provider.dart 
> the onAddTask function must _only_ add the task name if its not null.

**Make a PR only after you have been assigned the issue.**

![Screenshot_20221009-190538.jpg](https://user-images.githubusercontent.com/91426465/194759937-426ef2fd-d8ae-4238-beba-b8a5701ed2fb.jpg)

**Comment by Arsh-78** [comment]
hello I would like to work on this can you please assign it to me?
