### ISSUE TITLE
Enhance UI of task_card

### ISSUE THREAD

**Issue by Shubhi-Paul** [ACM-VIT/10-000-Hours#16]
In lib>view>widgets>task_card.dart  enhance the UI 

> proper padding
> text styling 
> background color
> card shape

**Comment by syprogrammer** [comment]
i have required knowledge please assign it to me

**Comment by pratikagr** [comment]
pls assign

**Comment by Him-anshuSharma** [comment]
> pls assign

go ahead

**Comment by Perumallpardhiv** [comment]
I want to try this, pls assign

**Comment by Perumallpardhiv** [comment]
> @Perumallpardhiv sorry someone is already assigned

ok
