### ISSUE TITLE
Pixel Overflow

### ISSUE THREAD

**Issue by Him-anshuSharma** [ACM-VIT/10-000-Hours#21]
fix the pixel overflow issue In lib>screens>on_boarding.dart

Recreate Issue:
1. Set initialroute: OnboardingScreen.id
2. Change screen orientation to landscape

**Comment by Arsh-78** [comment]
Hello I would like to work on this issue

**Comment by Him-anshuSharma** [comment]
@Arsh-78 go ahead

**Comment by Arsh-78** [comment]
hey I have raised a pr do let me know if some changes are needed

**Comment by Arsh-78** [comment]
Hey I have made the requested changes could u please check
