### ISSUE TITLE
Migrate from setstate to provider 

### ISSUE THREAD

**Issue by Him-anshuSharma** [ACM-VIT/10-000-Hours#22]
**Handle the state of the timer using the provider instead of the setstate.
provider class already exists in : lib>providers>timer_provider.dart**
<img src = "https://user-images.githubusercontent.com/51747937/194910998-d8a73419-7ecb-4642-9494-2631ea53be48.png" width="600" height="400">

**Update the file lib>view>screens>timer_screen.dart.**
<img src = "https://user-images.githubusercontent.com/51747937/194914154-cf321d87-1482-47bc-9444-ee2eace3b92d.png" width="600" height="400">

**Comment by SwaroopSambhayya** [comment]
I can take this up, can you assign?

**Comment by Him-anshuSharma** [comment]
@SwaroopSambhayya go ahead!

**Comment by SwaroopSambhayya** [comment]
Hi, I have created PR #26 , please review and merge
