### ISSUE TITLE
Add on boarding screen 

### ISSUE THREAD

**Issue by Shubhi-Paul** [ACM-VIT/10-000-Hours#3]
Create an onboarding.dart file in lib>view>screens. The onboarding screen can display about us information. Check the resources mentioned below.  Screen design and content are given below.

- Resources
1. https://pub.dev/packages/onboarding
2. Design: https://www.figma.com/file/vVwJyAjQ4pAX3FUZ4DrYch/onBoarding?node-id=1%3A26

**Comment by FaizFk** [comment]
Can you assign this task to me please

**Comment by Shubhi-Paul** [comment]
sure , go ahead.

**Comment by FaizFk** [comment]
Hey, would you mind if I use package other than onboarding package to accomplish this task??

**Comment by Shubhi-Paul** [comment]
Sure, just mention the details in the PR.

**Comment by FaizFk** [comment]
> Sure, just mention the details in the PR
Okay

**Comment by FaizFk** [comment]
Hi, So I have almost completed the task but do you want me to make the Skip button invisible and change the text of Next button to something like 'Continue' when the user is on last onboarding page?

**Comment by Shubhi-Paul** [comment]
You can play along with the UI making minor tweaks.

**Comment by Shubhi-Paul** [comment]
@FaizFk when u complete, make the PR in UI branch

**Comment by FaizFk** [comment]
Sorry I saw this message late, already sent the PR request to master branch.

**Comment by FaizFk** [comment]
I can sent the request again to UI branch, if you want?

**Comment by FaizFk** [comment]
Ok I have edited the request to UI branch.
