### ISSUE TITLE
Persist tasks on a database

### ISSUE THREAD

**Issue by LuanRoger** [ACM-VIT/10-000-Hours#31]
Currently the tasks is being saved on a Provider, but this don't garantee the task persistance when the user restart the app.

This work can be made by [Hive](https://pub.dev/packages/hive) or [ObjectBox](https://pub.dev/packages/objectbox) witch is two great databases for Flutter.

**Comment by Him-anshuSharma** [comment]
thanks @LuanRoger

**Comment by LuanRoger** [comment]
Can you assign to me?

**Comment by Him-anshuSharma** [comment]
@LuanRoger yes
