### ISSUE TITLE
Add Splash Screen

### ISSUE THREAD

**Issue by Him-anshuSharma** [ACM-VIT/10-000-Hours#4]
**Guidelines**
>Create splashscreen.dart in lib>views>screen
>Save svg file in  a separate folder in assets. **_assets>splashscreen_**
>Refer Figma file given below to implement SplashScreen
>Use SVG files only

**Figma file** :  https://www.figma.com/file/WH1FuL0AW1ag9SJr1QRgua/SplashScreen?node-id=1%3A4

**Comment by samitkapoor** [comment]
@Him-anshuSharma May I work on this issue?

**Comment by Him-anshuSharma** [comment]
> @Him-anshuSharma May I work on this issue?
> Yeah sure, Go ahead.

**Comment by Him-anshuSharma** [comment]
> @Him-anshuSharma May I work on this issue?

@samitkapoor 
Yeah sure, Go ahead. 
Make a PR in the UI branch

**Comment by samitkapoor** [comment]
@Him-anshuSharma okay 👍
