### ISSUE TITLE
Add functionality to delete button

### ISSUE THREAD

**Issue by Shubhi-Paul** [ACM-VIT/10-000-Hours#6]
In the lib>view>screens>timer_screen.dart add functionality to the delete button. 

> The delete button on tap must delete the specific task data.

Add a function  *deleteTask (int index)* in lib>providers>task_list_provider.dart to delete the taskData at that index from taskList .

 > you can get index from timer_screen

When the button is clicked -

1. delete the task i.e call the function 
2. navigate back to home_screen.dart

comment below if any doubts.

**Comment by Rohit-RA-2020** [comment]
Can I work On this?

**Comment by Shubhi-Paul** [comment]
sure, go ahead.
